import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// RootLayout.js

// import { Provider } from 'react-redux';
// // import { PersistGate } from 'redux-persist/integration/react';
// // import { persistStore } from 'redux-persist';
// import { store } from './(redux)/store'; // Import your Redux store
// // import { persistor , store } from './redux/store';
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   // const persistor = persistStore(store);

//   return (
//     <Provider store={store}>
//       {/* <PersistGate persistor={persistor} loading={null}> */}
//         <html lang="en">
//           <body className={inter.className}>
        
//             {children}
//           </body>
//         </html>
//       {/* </PersistGate> */}
//     </Provider>
//   );
// }

