version: '3.9'

services:
  Redis:
    container_name: redis
    image: redis/redis-stack
    ports:
      - 6379:6379
    restart: always

  Frontend:
    container_name: frontend
    image: nextjs-final
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - Redis

  Signup:
      container_name: signup
      image: signup-final
      build:
        context: ./backend/SignUp
        dockerfile: Dockerfile
      ports:
        - 8880:8880
      restart: always
      depends_on:
        - Redis      

  Login:
    container_name: login
    image: login-final
    build:
      context: ./backend/Login
      dockerfile: Dockerfile
    ports:
      - 8881:8881
    restart: always
    depends_on:
      - Redis

  Resend-Mail:
      container_name: resend-mail
      image: resend-mail-final
      build:
        context: ./backend/Resend-mail-verification
        dockerfile: Dockerfile
      ports:
        - 8882:8882
      restart: always
      depends_on:
        - Redis

  Forget-Password:
      container_name: forget-password
      image: forget-password-final
      build:
        context: ./backend/Forget-Password
        dockerfile: Dockerfile
      ports:
        - 8883:8883
      restart: always
      depends_on:
        - Redis    


  Verify-email-otp:
      container_name: verify-email-otp
      image:  verify-email-otp-final
      build:
        context: ./backend/Verify-Email-Otp
        dockerfile: Dockerfile
      ports:
        - 8884:8884
      restart: always
      depends_on:
        - Redis  